apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: soccer-ingress
  namespace: tenant-b
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: soccer.chelseablue.cloud
      http:
        paths:
          # FastAPI — /api/picks/today → fastapi service :8000 /picks/today
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: fastapi
                port:
                  number: 8000
          # React dashboard — everything else
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: dashboard
                port:
                  number: 80
