apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-nginx-to-soccer
  namespace: tenant-b
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values: [fastapi, dashboard]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - port: 8000
          protocol: TCP
        - port: 8080
          protocol: TCP
