"""phase3_confidence

Revision ID: 2d66bcd908c5
Revises: 43b3e8665768
Create Date: 2026-04-13 23:16:45.508514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d66bcd908c5'
down_revision: Union[str, Sequence[str], None] = '43b3e8665768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_espn_id', sa.String(), nullable=False),
    sa.Column('bet_type', sa.String(), nullable=False),
    sa.Column('w_model', sa.Float(), nullable=False),
    sa.Column('w_market', sa.Float(), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=True),
    sa.Column('fitted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calibration_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('bet_type', sa.String(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=True),
    sa.Column('brier_score', sa.Float(), nullable=True),
    sa.Column('n_samples', sa.Integer(), nullable=True),
    sa.Column('reliability_json', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ou_analysis', sa.Column('final_probability', sa.Float(), nullable=True))
    op.add_column('ou_analysis', sa.Column('edge_pct', sa.Float(), nullable=True))
    op.add_column('ou_analysis', sa.Column('kelly_fraction', sa.Float(), nullable=True))
    op.add_column('ou_analysis', sa.Column('steam_downgraded', sa.Boolean(), nullable=True))
    op.add_column('spread_predictions', sa.Column('final_probability', sa.Float(), nullable=True))
    op.add_column('spread_predictions', sa.Column('edge_pct', sa.Float(), nullable=True))
    op.add_column('spread_predictions', sa.Column('kelly_fraction', sa.Float(), nullable=True))
    op.add_column('spread_predictions', sa.Column('steam_downgraded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spread_predictions', 'steam_downgraded')
    op.drop_column('spread_predictions', 'kelly_fraction')
    op.drop_column('spread_predictions', 'edge_pct')
    op.drop_column('spread_predictions', 'final_probability')
    op.drop_column('ou_analysis', 'steam_downgraded')
    op.drop_column('ou_analysis', 'kelly_fraction')
    op.drop_column('ou_analysis', 'edge_pct')
    op.drop_column('ou_analysis', 'final_probability')
    op.drop_table('calibration_runs')
    op.drop_table('market_weights')
    # ### end Alembic commands ###
