"""add ml_artifacts

Revision ID: 43b3e8665768
Revises: ddcea6863f39
Create Date: 2026-04-13 22:54:05.918395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b3e8665768'
down_revision: Union[str, Sequence[str], None] = 'ddcea6863f39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('mae_home', sa.Float(), nullable=True),
    sa.Column('mae_away', sa.Float(), nullable=True),
    sa.Column('n_samples', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ml_artifacts')
    # ### end Alembic commands ###
