"""phase2_schema

Revision ID: 983c273e8635
Revises: ec6a35c0b004
Create Date: 2026-04-13 18:32:00.878344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '983c273e8635'
down_revision: Union[str, Sequence[str], None] = 'ec6a35c0b004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referee_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('league', sa.String(), nullable=True),
    sa.Column('fouls_per_tackle', sa.Float(), nullable=True),
    sa.Column('penalty_rate', sa.Float(), nullable=True),
    sa.Column('cards_per_game', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manager_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('tenure_games', sa.Integer(), nullable=True),
    sa.Column('draw_tendency_underdog', sa.Float(), nullable=True),
    sa.Column('tactical_archetype', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stadium_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('enclosure_rating', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tactical_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('archetype', sa.String(), nullable=True),
    sa.Column('ppda', sa.Float(), nullable=True),
    sa.Column('press_resistance', sa.Float(), nullable=True),
    sa.Column('set_piece_pct_scored', sa.Float(), nullable=True),
    sa.Column('aerial_win_rate', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draw_propensity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('manager_draw_tendency', sa.Float(), nullable=True),
    sa.Column('table_utility', sa.Float(), nullable=True),
    sa.Column('motivation_asymmetry', sa.Float(), nullable=True),
    sa.Column('defensive_trend', sa.Float(), nullable=True),
    sa.Column('ucl_aggregate_context', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id')
    )
    op.create_table('line_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('book', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('line', sa.Float(), nullable=False),
    sa.Column('odds', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # TimescaleDB hypertable for line_movement (PostgreSQL only)
    try:
        op.execute(
            "SELECT create_hypertable('line_movement', 'recorded_at', if_not_exists => TRUE)"
        )
        op.execute(
            "ALTER TABLE line_movement SET (timescaledb.compress, "
            "timescaledb.compress_segmentby = 'fixture_id,book,market')"
        )
        op.execute(
            "SELECT add_compression_policy('line_movement', INTERVAL '30 days')"
        )
    except Exception:
        pass  # SQLite / TimescaleDB not installed
    op.create_table('player_impact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('xg_contribution_pct', sa.Float(), nullable=True),
    sa.Column('is_absent', sa.Boolean(), nullable=True),
    sa.Column('is_gk', sa.Boolean(), nullable=True),
    sa.Column('psxg_plus_minus', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rotation_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('rotation_probability', sa.Float(), nullable=True),
    sa.Column('ucl_fixture_id', sa.Integer(), nullable=True),
    sa.Column('hours_between', sa.Float(), nullable=True),
    sa.Column('overridden_by_lineup', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['ucl_fixture_id'], ['fixtures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rotation_flags')
    op.drop_table('player_impact')
    op.drop_table('line_movement')
    op.drop_table('draw_propensity')
    op.drop_table('tactical_profiles')
    op.drop_table('stadium_profiles')
    op.drop_table('manager_profiles')
    op.drop_table('referee_profiles')
    # ### end Alembic commands ###
