"""add_league_calibration_and_monte_carlo_runs

Revision ID: ddcea6863f39
Revises: 983c273e8635
Create Date: 2026-04-13 22:41:48.344835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddcea6863f39'
down_revision: Union[str, Sequence[str], None] = '983c273e8635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_calibration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_espn_id', sa.String(), nullable=False),
    sa.Column('rho', sa.Float(), nullable=False),
    sa.Column('home_advantage', sa.Float(), nullable=False),
    sa.Column('attack_scale', sa.Float(), nullable=False),
    sa.Column('defense_scale', sa.Float(), nullable=False),
    sa.Column('fitted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_espn_id')
    )
    op.create_table('monte_carlo_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('lambda_home', sa.Float(), nullable=False),
    sa.Column('lambda_away', sa.Float(), nullable=False),
    sa.Column('rho', sa.Float(), nullable=False),
    sa.Column('home_win_prob', sa.Float(), nullable=True),
    sa.Column('draw_prob', sa.Float(), nullable=True),
    sa.Column('away_win_prob', sa.Float(), nullable=True),
    sa.Column('over_15_prob', sa.Float(), nullable=True),
    sa.Column('over_25_prob', sa.Float(), nullable=True),
    sa.Column('over_35_prob', sa.Float(), nullable=True),
    sa.Column('scoreline_json', sa.Text(), nullable=True),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monte_carlo_runs')
    op.drop_table('league_calibration')
    # ### end Alembic commands ###
