"""phase1_schema

Revision ID: ec6a35c0b004
Revises: 88f7eee46110
Create Date: 2026-04-13 07:08:43.205874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec6a35c0b004'
down_revision: Union[str, Sequence[str], None] = '88f7eee46110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('goals_scored_avg', sa.Float(), nullable=False),
    sa.Column('goals_conceded_avg', sa.Float(), nullable=False),
    sa.Column('spread_cover_rate', sa.Float(), nullable=True),
    sa.Column('ou_hit_rate_15', sa.Float(), nullable=True),
    sa.Column('ou_hit_rate_25', sa.Float(), nullable=True),
    sa.Column('ou_hit_rate_35', sa.Float(), nullable=True),
    sa.Column('xg_scored_avg', sa.Float(), nullable=True),
    sa.Column('xg_conceded_avg', sa.Float(), nullable=True),
    sa.Column('matches_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ou_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('line', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('ev_score', sa.Float(), nullable=True),
    sa.Column('confidence_tier', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spread_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('team_side', sa.String(), nullable=False),
    sa.Column('goal_line', sa.Float(), nullable=False),
    sa.Column('cover_probability', sa.Float(), nullable=True),
    sa.Column('push_probability', sa.Float(), nullable=True),
    sa.Column('ev_score', sa.Float(), nullable=True),
    sa.Column('confidence_tier', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('odds_snapshots', sa.Column('spread_home_line', sa.Float(), nullable=True))
    op.add_column('odds_snapshots', sa.Column('spread_home_odds', sa.Float(), nullable=True))
    op.add_column('odds_snapshots', sa.Column('spread_away_line', sa.Float(), nullable=True))
    op.add_column('odds_snapshots', sa.Column('spread_away_odds', sa.Float(), nullable=True))
    op.add_column('results', sa.Column('red_card_minute', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'red_card_minute')
    op.drop_column('odds_snapshots', 'spread_away_odds')
    op.drop_column('odds_snapshots', 'spread_away_line')
    op.drop_column('odds_snapshots', 'spread_home_odds')
    op.drop_column('odds_snapshots', 'spread_home_line')
    op.drop_table('spread_predictions')
    op.drop_table('ou_analysis')
    op.drop_table('form_cache')
    # ### end Alembic commands ###
